[package]
name = "webring"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_http = "0.17.0"
serde_json = "1.0.145"

[dev-dependencies]
async-io = { version = "2.6.0", features = ["tracing"] }
