name: Update Lambda Environment Variables

on:
  push:
    branches:
      - main
    paths:
      - sitelist
      - .github/workflows/update_sitelist.yml

env:
  AWS_REGION: us-east-1
  NEXT_NAME: webring_manager_next
  PREV_NAME: webring_manager_prev
  SITELIST: ./sitelist

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update environment variable for next lambda
        run: aws lambda update-function-configuration --function-name $NEXT_NAME --environment "Variables={SITES='$(xargs -a $SITELIST)'}"
      - name: Update environment variable for prev lambda
        run: aws lambda update-function-configuration --function-name $PREV_NAME --environment "Variables={SITES='$(xargs -a $SITELIST)'}"
      - name: Invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id E1K7F5YQJX538J --paths "/webring/*"
